baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Random notes'
theme = 'cactus'
GoogleAnalytics = ""


[Params]
  [Comments]
    enabled = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'


